<?php
declare(strict_types = 1);

namespace Cerberus\Core;

use MabeEnum\Enum;

class CategoryType extends Enum
{
    const ID_ATTRIBUTE_CATEGORY_RESOURCE = 'ID_ATTRIBUTE_CATEGORY_RESOURCE';

    const ID_DATATYPE_ARRAY = 'ID_DATATYPE_ARRAY';
    const ID_DATATYPE_BOOLEAN = 'ID_DATATYPE_BOOLEAN';
    const ID_DATATYPE_DATETIME = 'ID_DATATYPE_DATETIME';
    const ID_DATATYPE_DOUBLE = 'ID_DATATYPE_DOUBLE';
    const ID_DATATYPE_INTEGER = 'ID_DATATYPE_INTEGER';
    const ID_DATATYPE_STRING = 'ID_DATATYPE_STRING';
}